# frozen_string_literal: true

ruby "~> 3.0"

source ENV.fetch('RUBYGEMS_MIRROR', 'https://rubygems.org')

gem 'aws-sdk-eks',         '~> 1.83'
gem 'aws-sdk-kms',         '~> 1.63'
gem 'base64',              '~> 0.2'
gem 'deep_merge',          '~> 1.2',    '>= 1.2.2'
gem 'faraday-retry',       '~> 2.2'
gem 'irb',                 '~> 1.15'
gem 'kramdown',            '~> 2.4'
gem 'kramdown-parser-gfm', '~> 1.1'
gem 'logger',              '~> 1.6'
gem 'rbnacl',              '~> 7.1'
gem 'octokit',             '~> 8.1'
gem 'semantic',            '~> 1.6',    '>= 1.6.1'
gem 'tty-command',         '~> 0.10.1'
gem 'tty-file',            '~> 0.10.0'
gem 'tty-logger',          '~> 0.6.0'
gem 'tty-prompt',          '~> 0.23.1'
gem 'tty-screen',          '~> 0.8.1'
gem 'tty-which',           '~> 0.5.0'

gem 'contracts',           '~> 0.17'
gem 'diff-lcs',            '~> 1.5'
gem 'facets',              '~> 3.1'
gem 'git',                 '~> 1.13',   '>= 1.13.2'
gem 'hashdiff',            '~> 1.0',    '>= 1.0.1'
gem 'openapi_parser',      '~> 1.0'
gem 'tty-box',             '~> 0.7.0'
gem 'tty-color',           '~> 0.6.0'
gem 'tty-config',          '~> 0.6.0'
gem 'tty-cursor',          '~> 0.7.1'
gem 'tty-editor',          '~> 0.7.0'
gem 'tty-font',            '~> 0.5.0'
gem 'tty-link',            '~> 0.1.1'
gem 'tty-markdown',        '~> 0.7.0'
gem 'tty-option',          '~> 0.2.0'
gem 'tty-pager',           '~> 0.14.0'
gem 'tty-pie',             '~> 0.4.0'
gem 'tty-platform',        '~> 0.3.0'
gem 'tty-progressbar',     '~> 0.18.2'
gem 'tty-reader',          '~> 0.9.0'
gem 'tty-spinner',         '~> 0.9.3'
gem 'tty-table',           '~> 0.12.0'
gem 'tty-tree',            '~> 0.4.0'
