name: build-sync-pwd-image

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            luistt/sync-pwd
          tags: |
            type=semver,pattern=v{{version}}
      
#      - name: "Read Secrets"
#        uses: rancher-eio/read-vault-secrets@main
#        with:
#          secrets: |
#            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
#            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          #context: "{{defaultContext}}:POC-sync-pwd"
          tags: ${{ steps.meta.outputs.tags }}